version: 2.1
jobs:
  build:
    working_directory: /
    docker:
      - image: hello-public-repo:latest
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID $DOCKER_HUB_PWD
            docker push $DOCKER_HUB_USER_ID/hello-public-repo:latest