version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: mauroorlando
          password: $DOCKERHUB_PASSWORD
    steps:

      - setup_remote_docker:
          version: 19.03.13

      - run: |
          TAG=latest
          docker build -t mauroorlando/hello-public-repo:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push mauroorlando/hello-public-repo:$TAG